# Pre processing of Abalone dataset to make imbalance ratio of training and testing same

In [30]:
import numpy as np
from numpy import linalg
import pandas as pd

In [31]:
train = pd.read_table("page-blocks.data", sep="\s+",header=None)
train.head()

0   1    2      3      4      5     6   7   8   9   10
0   5   7   35  1.400  0.400  0.657  2.33  14  23   6   1
1   6   7   42  1.167  0.429  0.881  3.60  18  37   5   1
2   6  18  108  3.000  0.287  0.741  4.43  31  80   7   1
3   5   7   35  1.400  0.371  0.743  4.33  13  26   3   1
4   6   3   18  0.500  0.500  0.944  2.25   9  17   4   1

In [32]:
train[10] = train[10].map({5: 1, 1:-1,2:-1,3:-1,4:-1})
print(train[10])

0      -1
1      -1
2      -1
3      -1
4      -1
5      -1
6      -1
7      -1
8      -1
9      -1
10     -1
11     -1
12     -1
13     -1
14     -1
15     -1
16     -1
17     -1
18     -1
19     -1
20     -1
21     -1
22     -1
23     -1
24     -1
25     -1
26     -1
27     -1
28     -1
29     -1
       ..
5443   -1
5444   -1
5445   -1
5446   -1
5447   -1
5448   -1
5449   -1
5450   -1
5451   -1
5452   -1
5453   -1
5454   -1
5455   -1
5456   -1
5457   -1
5458   -1
5459   -1
5460   -1
5461   -1
5462   -1
5463   -1
5464   -1
5465   -1
5466   -1
5467   -1
5468   -1
5469   -1
5470   -1
5471   -1
5472   -1
Name: 10, Length: 5473, dtype: int64


In [33]:
train=np.asarray(train)

In [34]:
min_train=np.zeros((115,11))
max_train=np.zeros((5358,11))
min_train=np.asarray(min_train)
max_train=np.asarray(max_train)

In [62]:
k=0
l=0
for i in range(0,5473):
    if(train[i][10]==1):
        for j in range(0,11):
            min_train[k][j]=train[i][j]   
        k=k+1
    else :
        for j in range(0,11):
            max_train[l][j]=train[i][j]
        l=l+1

In [63]:
print(max_train)

[[  5.   7.  35. ...  23.   6.  -1.]
 [  6.   7.  42. ...  37.   5.  -1.]
 [  6.  18. 108. ...  80.   7.  -1.]
 ...
 [  6.  95. 570. ... 519. 104.  -1.]
 [  7.  41. 287. ... 230.  45.  -1.]
 [  8.   1.   8. ...   8.   1.  -1.]]


In [64]:
data1=np.zeros((1094,11))
data2=np.zeros((1094,11))
data3=np.zeros((1095,11))
data4=np.zeros((1095,11))
data5=np.zeros((1095,11))

In [65]:
for i in range(0,115):
    for j in range(0,11):
        if(i<23):
            data1[i][j]=min_train[i][j]
        elif(22<i and i<46):
            data2[i-23][j]=min_train[i][j]
        elif(45<i and i<69):
            data3[i-46][j]=min_train[i][j]
        elif(68<i and i<92):
            data4[i-69][j]=min_train[i][j]
        elif(91<i and i<115):
            data5[i-92][j]=min_train[i][j]
    
        
print(data5[24])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [66]:
for i in range(0,5358):
    for j in range(0,11):
        if(i<1071):
            data1[i+23][j]=max_train[i][j]
        elif(1070<i and i<2142):
            data2[i-1048][j]=max_train[i][j]
        elif(2141<i and i<3214):
            data3[i-2119][j]=max_train[i][j]
        elif(3213<i and i<4286):
            data4[i-3191][j]=max_train[i][j]
        elif(4285<i and i<5358):
            data5[i-4263][j]=max_train[i][j]   
print(data5[1000])

[  9.     33.    297.      3.667   0.347   0.929   2.58  103.    276.
  40.     -1.   ]


In [67]:
print(data5.shape)
data5

(1095, 11)


array([[ 1.010e+02,  9.900e+01,  9.999e+03, ...,  7.780e+03,  6.910e+02,
         1.000e+00],
       [ 3.000e+01,  6.000e+01,  1.800e+03, ...,  8.230e+02,  1.500e+02,
         1.000e+00],
       [ 3.200e+01,  1.060e+02,  3.392e+03, ...,  1.341e+03,  1.470e+02,
         1.000e+00],
       ...,
       [ 6.000e+00,  9.500e+01,  5.700e+02, ...,  5.190e+02,  1.040e+02,
        -1.000e+00],
       [ 7.000e+00,  4.100e+01,  2.870e+02, ...,  2.300e+02,  4.500e+01,
        -1.000e+00],
       [ 8.000e+00,  1.000e+00,  8.000e+00, ...,  8.000e+00,  1.000e+00,
        -1.000e+00]])

In [68]:
import csv
with open('newab.csv', 'w') as csvFile:
    writer = csv.writer(csvFile)
    writer.writerows(data1)

csvFile.close()

In [69]:
import csv
with open('newab.csv', 'a') as csvFile:
    writer = csv.writer(csvFile)
    writer.writerows(data2)

csvFile.close()

In [70]:
import csv
with open('newab.csv', 'a') as csvFile:
    writer = csv.writer(csvFile)
    writer.writerows(data3)

csvFile.close()

In [71]:
import csv
with open('newab.csv', 'a') as csvFile:
    writer = csv.writer(csvFile)
    writer.writerows(data4)

csvFile.close()

In [72]:
import csv
with open('newab.csv', 'a') as csvFile:
    writer = csv.writer(csvFile)
    writer.writerows(data5)

csvFile.close()

In [73]:
df = pd.read_csv("newab.csv")
#checking the number of empty rows in th csv file
print (df.isnull().sum())
#Droping the empty rows
modifiedDF = df.dropna()
#Saving it to the csv file 
modifiedDF.to_csv('modifiedpage.csv',index=False)

48.0       0
402.0      0
19296.0    0
8.375      0
0.055      0
0.094      0
4.13       0
1058.0     0
1814.0     0
256.0      0
1.0        0
dtype: int64
