# Pre processing of Abalone dataset to make imbalance ratio of training and testing same

In [2]:
import numpy as np
from numpy import linalg
import pandas as pd

In [4]:
train = pd.read_csv("haberman.csv",header=None)
train.head()

0   1  2  3
0  30  64  1  1
1  30  62  3  1
2  30  65  0  1
3  31  59  2  1
4  31  65  4  1

In [6]:
train[3] = train[3].map({2:1,1:-1})
print(train[3])

0     -1
1     -1
2     -1
3     -1
4     -1
5     -1
6     -1
7      1
8      1
9     -1
10    -1
11    -1
12    -1
13    -1
14    -1
15    -1
16    -1
17    -1
18    -1
19    -1
20    -1
21    -1
22    -1
23    -1
24     1
25    -1
26    -1
27    -1
28    -1
29    -1
      ..
276   -1
277   -1
278   -1
279   -1
280   -1
281    1
282   -1
283   -1
284   -1
285    1
286    1
287   -1
288   -1
289   -1
290   -1
291   -1
292   -1
293    1
294   -1
295   -1
296   -1
297   -1
298   -1
299    1
300   -1
301   -1
302   -1
303   -1
304    1
305    1
Name: 3, Length: 306, dtype: int64


In [7]:
train=np.asarray(train)

In [19]:
min_train=np.zeros((81,4))
max_train=np.zeros((225,4))
min_train=np.asarray(min_train)
max_train=np.asarray(max_train)

In [20]:
k=0
l=0
for i in range(0,306):
    if(train[i][3]==1):
        for j in range(0,4):
            min_train[k][j]=train[i][j]   
        k=k+1
    else :
        for j in range(0,4):
            max_train[l][j]=train[i][j]
        l=l+1

In [21]:
print(min_train)

[[34. 59.  0.  1.]
 [34. 66.  9.  1.]
 [38. 69. 21.  1.]
 [39. 66.  0.  1.]
 [41. 60. 23.  1.]
 [41. 64.  0.  1.]
 [41. 67.  0.  1.]
 [42. 69.  1.  1.]
 [42. 59.  0.  1.]
 [43. 58. 52.  1.]
 [43. 59.  2.  1.]
 [43. 64.  0.  1.]
 [43. 64.  0.  1.]
 [44. 64.  6.  1.]
 [44. 58.  9.  1.]
 [44. 63. 19.  1.]
 [45. 65.  6.  1.]
 [45. 66.  0.  1.]
 [45. 67.  1.  1.]
 [46. 58.  2.  1.]
 [46. 69.  3.  1.]
 [46. 62.  5.  1.]
 [46. 65. 20.  1.]
 [47. 63. 23.  1.]
 [47. 62.  0.  1.]
 [47. 65.  0.  1.]
 [48. 58. 11.  1.]
 [48. 58. 11.  1.]
 [48. 67.  7.  1.]
 [49. 63.  0.  1.]
 [49. 64. 10.  1.]
 [50. 63. 13.  1.]
 [50. 64.  0.  1.]
 [51. 59. 13.  1.]
 [51. 59.  3.  1.]
 [52. 69.  3.  1.]
 [52. 59.  2.  1.]
 [52. 62.  3.  1.]
 [52. 66.  4.  1.]
 [53. 58.  4.  1.]
 [53. 65.  1.  1.]
 [53. 59.  3.  1.]
 [53. 60.  9.  1.]
 [53. 63. 24.  1.]
 [53. 65. 12.  1.]
 [54. 60. 11.  1.]
 [54. 65. 23.  1.]
 [54. 65.  5.  1.]
 [54. 68.  7.  1.]
 [55. 63.  6.  1.]
 [55. 68. 15.  1.]
 [56. 65.  9.  1.]
 [56. 66.  3

In [23]:
data1=np.zeros((61,4))
data2=np.zeros((61,4))
data3=np.zeros((61,4))
data4=np.zeros((61,4))
data5=np.zeros((62,4))

In [28]:
for i in range(0,81):
    for j in range(0,4):
        if(i<16):
            data1[i][j]=min_train[i][j]
        elif(15<i and i<32):
            data2[i-16][j]=min_train[i][j]
        elif(31<i and i<48):
            data3[i-32][j]=min_train[i][j]
        elif(47<i and i<64):
            data4[i-48][j]=min_train[i][j]
        elif(63<i and i<81):
            data5[i-64][j]=min_train[i][j]
    
        
print(data5[17])

[0. 0. 0. 0.]


In [31]:
for i in range(0,225):
    for j in range(0,4):
        if(i<45):
            data1[i+16][j]=max_train[i][j]
        elif(44<i and i<90):
            data2[i-29][j]=max_train[i][j]
        elif(89<i and i<135):
            data3[i-74][j]=max_train[i][j]
        elif(134<i and i<180):
            data4[i-119][j]=max_train[i][j]
        elif(179<i and i<225):
            data5[i-163][j]=max_train[i][j]   
print(data5[61])

[77. 65.  3. -1.]


In [32]:
print(data5.shape)
data5

(62, 4)


array([[62., 65., 19.,  1.],
       [63., 60.,  1.,  1.],
       [65., 58.,  0.,  1.],
       [65., 61.,  2.,  1.],
       [65., 62., 22.,  1.],
       [65., 66., 15.,  1.],
       [66., 58.,  0.,  1.],
       [66., 61., 13.,  1.],
       [67., 64.,  8.,  1.],
       [67., 63.,  1.,  1.],
       [69., 67.,  8.,  1.],
       [70., 58.,  0.,  1.],
       [70., 58.,  4.,  1.],
       [72., 63.,  0.,  1.],
       [74., 65.,  3.,  1.],
       [78., 65.,  1.,  1.],
       [83., 58.,  2.,  1.],
       [63., 61.,  0., -1.],
       [63., 62.,  0., -1.],
       [63., 63.,  0., -1.],
       [63., 63.,  0., -1.],
       [63., 66.,  0., -1.],
       [63., 61.,  9., -1.],
       [63., 61., 28., -1.],
       [64., 58.,  0., -1.],
       [64., 65., 22., -1.],
       [64., 66.,  0., -1.],
       [64., 61.,  0., -1.],
       [64., 68.,  0., -1.],
       [65., 58.,  0., -1.],
       [65., 64.,  0., -1.],
       [65., 67.,  0., -1.],
       [65., 59.,  2., -1.],
       [65., 64.,  0., -1.],
       [65., 6

In [33]:
import csv
with open('newab.csv', 'w') as csvFile:
    writer = csv.writer(csvFile)
    writer.writerows(data1)

csvFile.close()

In [34]:
import csv
with open('newab.csv', 'a') as csvFile:
    writer = csv.writer(csvFile)
    writer.writerows(data2)

csvFile.close()

In [35]:
import csv
with open('newab.csv', 'a') as csvFile:
    writer = csv.writer(csvFile)
    writer.writerows(data3)

csvFile.close()

In [36]:
import csv
with open('newab.csv', 'a') as csvFile:
    writer = csv.writer(csvFile)
    writer.writerows(data4)

csvFile.close()

In [37]:
import csv
with open('newab.csv', 'a') as csvFile:
    writer = csv.writer(csvFile)
    writer.writerows(data5)

csvFile.close()

In [38]:
df = pd.read_csv("newab.csv")
#checking the number of empty rows in th csv file
print (df.isnull().sum())
#Droping the empty rows
modifiedDF = df.dropna()
#Saving it to the csv file 
modifiedDF.to_csv('modifiedhaberman.csv',index=False)

34.0    0
59.0    0
0.0     0
1.0     0
dtype: int64
